### ISSUE TITLE
Reset of error handler in Promise\fatalError

### ISSUE THREAD

**Issue by CharlotteDunois** [reactphp/promise#131]
Is there any reason why the internal function `fatalError` resets the error handler, even though the library does not even set one in the first place? A nasty side effect of this is that it removes an user defined error handler - in my case would that be a throwing error handler, leading to regular PHP errors, which can't be handled through try-catch.

https://github.com/reactphp/promise/blob/c1aad8e65d6406fd361f8975194a094d06c83793/src/functions.php#L209-L220

The relevant [commit](https://github.com/reactphp/promise/commit/23cd28cd2d42105fb5442c2c2caec81026ddd550) for this does not mention why a reset is necessary.

**Comment by jsor** [comment]
The intention is, that errors ending here are not being handled properly before (eg. and exception thrown in the `$onRejected` callback registered via `done()`) and thus must abort the program. This is a programming error, similar to an uncaught exception.

**Comment by CharlotteDunois** [comment]
That is the intention of the whole function, yes. But I dont really get why there is a try catch block. If I throw an exception from my error handler, a library shouldn't catch it, unset my error handler and trigger it as regular error again. The intention of trying to abort the program and overwrite an user defined behaviour of what happens when a PHP error gets triggered shouldn't be modified to get the intended result. Exactly because `done` does not catch an exception I could use this behaviour to fallback to some sort of top level catch block to apply custom logic. However due to the behaviour of trying to catch an exception from triggering an error, the user defined error handler gets overwritten. In the end if the error handler just does something else than triggering an exception (like just log the error and good), your intentions are never executed. In my opinion the try catch block should be removed, exactly because you can never exactly fulfill it and because you overwrite an user defined behaviour.

**Comment by jsor** [comment]
The second argument of `done()` **_is_** your top level catch block. If there is an exception thrown in that block, it is equivalent if code in the top level catch block of an synchronous application throws (which results in an fatal error for an uncaught exception).

In an promise-based asynchronous application, you should avoid try-catch blocks because you most likely also use an event loop and the code throwing might be in a different call stack than the try-catch block. The promise API mimics exactly the try-catch-finally blocks from synchronous applications.

```php
try {
    $response = app();
    echo $response;
} catch (\Throwable $e) {
    logUnhandledException($e);
    echo "Unhandled fatal error $e";
} finally {
   echo "Thank you for flying with us!";
}
```

is the synchronous equivalent to the following async one:

```php
app()
    ->then(function ($response) {
        echo $response;
    })
    ->otherwise(function (\Throwable $e) {
        logUnhandledException($e);
        echo "Unhandled fatal error $e";
    })
    ->always(function () {
       echo "Thank you for flying with us!";
    })
    ->done()
;
```

_(The above code also demostrates my personal preference to explicitely "catch" exceptions with `otherwise()` and just end the promise chain with `done()`)_

In both cases, if `logUnhandledException()` throws, it will result in an fatal error. `done()` here is only a mechanism to not swallow the exception thrown inside the `otherwise()`callback.

**Comment by CharlotteDunois** [comment]
It may be a programming error, but you're removing any fault tolerance an application had by making it crash completely. Any production application will run under a supervisor and will be restarted. And this cycle will repeat and repeat. I don't even think a library should touch any error or exception handlers at all, may it be a programming or fatal error at all.

Let the application handle it. If I were forced to upgrade to a future promise v3 with this code and I want to restore fault tolerance in my application, I'd have three options:
1) Use a different promise library who doesn't play with my handlers.
2) Maintain a fork without this code.
3) Replace `set_error_handler` with a no-op using some sort of low-level PHP extension.

However all these options are bad and I don't think a library should make the decision whether the application should crash or not. I get what you want to achieve, but it doesn't solve any specific problem, it just creates new ones.

**Comment by jsor** [comment]
Since you closed this issue, i just wanted to ask if i explained the intention of this behaviour good enough? I'm still interested in your use case. It is still prefectly possible that we miss something.

**Comment by CharlotteDunois** [comment]
You explained it. I understood it, but I don't think that a library should ever mess with error handlers. It's not something that a library should care about. It's an application's responsibility to handle this.

I'm not per se against making it a "pseudo" fatal error when the `done` handler throws an exception. I'm against messing with error handler because it works entirely against an application's philosophy.

But I don't think that my sole opinion for this philosophy would change anything, so I decided to not further persue it.

**Comment by jsor** [comment]
I definitely see you point and we probably can do better here. The intention of the change was, to not let any exceptions bubble out of the callbacks because it's handling is then unpredictable. Depending on the situation, it might end up in the recjection chain, bubble out etc. See also https://github.com/reactphp/promise/issues/88 which led to this change. That's the reason we do not allow the error handler to throw here.

An alternative approach could be to wrap the exception in something like an `FatalErrorException` so the error handler can detect it and act accordingly, eg. just log just this exception and rethrow all other errors as exceptions.

**Comment by CharlotteDunois** [comment]
The decision to convert an error to an exception was however an application decision. If that now leads to exceptions bubbling up to `reject` or `resolve` callbacks, then that's unfortunate but shouldn't lead to library workarounds and explicit overrides. The exception stack trace shows where it was initially thrown (in the error handler with the original error) and thus leads to (hopefully) appropriate application developer actions.

I see why that change was necessary and I do think that something should be done, but not at the expense of explicitely working against an application. My error handler explicitely converts an error to an exception and if that now goes through all blocks and leads to an uncaught exception, then the Sentry client I've integrated would report this. However an unset error handler can't inform anyone of an error, because Sentry was never informed about it. The handler was explicitely unset to allow slipping through. Resulting to unreported bugs, application crash and downtime. Headache for every developer involved in the application.

The current behaviour isn't even to my knowledge documented, leading to even more headache because no one knows why the application error handler wasn't triggered (correctly).

I'm totally for making an exception class and letting that explicitely through all promise chains (if that's feasible) - or if not possible, let the user decide what action to take. If it's still a thrown exception, then the user has to deal with the consequences.

But just unsetting an application error handler makes no one happy.

**Comment by clue** [comment]
@CharlotteDunois Thanks for raising this issue, I agree that this looks weird. Can you gist the problem you're seeing, so we can take a look at how this could potentially be improved? :+1:
