### ISSUE TITLE
Fullfilled or Rejected promise and then method

### ISSUE THREAD

**Issue by Logioniz** [reactphp/promise#147]
I have infinit loop when execute this simple example:

```php
<?php
$loader = require __DIR__ . '/vendor/autoload.php';

use React\Promise\Deferred;

$loop = new React\EventLoop\StreamSelectLoop();

$d = new Deferred();
$d->resolve('resolve');

$connector = new React\Socket\Connector($loop);
$promise = $connector->connect('google.com:80')->then(function (React\Socket\ConnectionInterface $connection) use ($loop) {
    var_dump('second');
    $loop->stop();
    return $connection;
});
var_dump('first');
$loop->run();

React\Promise\resolve($d->promise())
    ->then(function ($e) use ($loop) {
        var_dump('fourth');
        $loop->stop();
    });
var_dump('third');
$loop->run();
```

The result of the execution is:
```
$ php test.php 
string(5) "first"
string(6) "second"
string(6) "fourth"
string(5) "third"
^C
```
Expected execution order is:
first
second
third
fourth

I think the problem is in the THEN method, which should be in futureTick (next tick), but callback called immediately.

**Comment by jsor** [comment]
Promise resolution is synchronous by default, except when you resolve them asynchronously.

```php
$loop->futureTick(function () use ($d) {
    $d->resolve('resolve');
});
```

**Comment by Logioniz** [comment]
I think that **then** method must be asynchronous.

I think it fix all problem here.

I found another implementation of promise in popular framework mojolicious (sorry this is perl but code implementation is very simple). The method **then** is called there asynchronously. [Link to code](https://metacpan.org/release/Mojolicious/source/lib/Mojo/Promise.pm#L123).

What do you think about it?

**Comment by jsor** [comment]
Could you explain why resolution should be asynchronous and what exact problem would be solved?

**Comment by Logioniz** [comment]
I write tests where i use run and stop method of event loop many times.
Simplified code of my tests looks like it is written in the first post.
**Then** method should be non-blocking because of expected behavior.

**Comment by WyriHaximus** [comment]
Bear in mind that a promise is nothing more then a communication channel. It only does things when you it to. So while it's own execution is synchronous it enables us to write non-blocking code. The `then` does nothing more then set the callbacks to run when the promise resolves, and run it when the promise already resolved. Consider the following:

`$deferred = new Deferred();`

We get a promise from the deferred object and set a resolve handler on it:

```php
$deferred->promise()->then(function () {
    echo 'resolved!', PHP_EOL;
});
```

Now up to this point nothing is echoed. But once we call `$deferred->resolve();` `resolved!` will be echoed. So when you call it like this `resolved!` will be echoed the moment you call then:

```php
$deferred = new Deferred();
$deferred->resolve();
$deferred->promise()->then(function () {
    echo 'resolved!', PHP_EOL;
});
```

And that is exactly what your example does, it resolves the promise the moment you create it. Which is the expected behaviour.

Also the reason why you have an infinite loop with that example is because you have an open connection with Google and it takes a while for the timeout to kick in and the connection to close.

**Comment by Logioniz** [comment]
> Also the reason why you have an infinite loop with that example is because you have an open connection with Google and it takes a while for the timeout to kick in and the connection to close.

I repeat, I am writing tests. The connection is established in the setup method, and the connection is closed in the teardown method. This is logical for me. The effect is the same.

> And that is exactly what your example does, it resolves the promise the moment you create it. Which is the expected behaviour.

It looks like for different people the expected behavior is different.  For this reason, I am going to close the topic.

I have a question, how to use assert in event loop or what if exception appears in event loop in tests? At this point, there is an infinite loop again.

**Comment by WyriHaximus** [comment]
@Logioniz these tests? https://github.com/Logioniz/reactphp-memcached/blob/master/tests/FunctionalTest.php#L242

**Comment by Logioniz** [comment]
Yes.

**Comment by WyriHaximus** [comment]
Cheers, slowly working on a PR with some suggestions :smile:
