### ISSUE TITLE
PHP 8.0 Deprecation Notice

### ISSUE THREAD

**Issue by SerafimArts** [reactphp/promise#181]
This error is currently being reproduced on PHP 8.0:

`react/promise: dev-master`:
> Method ReflectionParameter::getClass() is deprecated in ...\react\promise\src\functions.php on line 345

Similar behavior on latest `react/promise: 2.8` version.

**Comment by clue** [comment]
@SerafimArts Thanks for reporting, can confirm this raises a deprecation notice when using the `otherwise()` method, but does otherwise work just fine. This is being work on in #176, we'll work this out as soon as time allows :+1: 

I'm closing this for now as progress is already being tracked, please feel free to come back if you have more details and we can always reopen this :+1:
