### ISSUE TITLE
Creating Promise out of an event emitter ?

### ISSUE THREAD

**Issue by Adirelle** [reactphp/promise#37]
Not sure if this is the right project for this, as this depends of both Promise and Evenement.

Having heavily worked with reactphp recently, I ended up creating Promises out of EventEmitters a lot. The typical piece of code looks like this:

```php
$deferred = new Deferred();

$emitter->once('data', [$deferred, 'resolve']);
$emitter->once('error', [$deferred, 'reject']);

return $deferred->promise()
  ->always(function() use ($deferred, $emitter) {
    // Remove listener to avoid leaking memory
    $emitter->removeListener('data', [$deferred, 'resolve']);
    $emitter->removeListener('error', [$deferred, 'reject']);
  });
```

And this doesn't even handle cancellations.

Wouldn't some kind of EventListenerPromise be useful in the Promise library ?

**Comment by clue** [comment]
> Having heavily worked with reactphp recently, I ended up creating Promises out of EventEmitters a lot. The typical piece of code looks like this:

This looks interesting. Personally, I've never had a use for obtaining a promise (a single value) from a stream of (any number of) events. However, considering the `$emitter` could be more like a high-level protocol parser emitter than an underlying stream emitter, I think it makes perfect sense to have your suggested code in a reusable library.

> Not sure if this is the right project for this, as this depends of both Promise and Evenement.

This is probably one of the main concerns here. In the past, this library has avoided introducing additional dependencies because it can be used in quite a few different scenarios.

Instead, it embraces building an ecosystem around it. Quite a few libraries have already been built on top of it, among of the more recent additions is my [clue/promise-timer](https://github.com/clue/promise-timer) library (which essentially binds the React's Promise component with its EventLoop component.

How about starting off with a dedicated library? Once this turns out to be useful to a lot of people, we *could* (eventually) easily migrate it to the React project in order to increase its visibility.

**Comment by Adirelle** [comment]
> How about starting off with a dedicated library? Once this turns out to be useful to a lot of people, we could (eventually) easily migrate it to the React project in order to increase its visibility.

I might try this.

**Comment by jsor** [comment]
There is also [BufferedSink](https://github.com/reactphp/stream/blob/master/src/BufferedSink.php) which creates a promise from a stream.

**Comment by Adirelle** [comment]
Well, I actually use it for "high-level" protocols, e.g. [gpsd](http://www.catb.org/gpsd/) protocol handler that emits events from received [json messages](http://catb.org/gpsd/gpsd_json.html), so BufferedSink isn't an option.

**Comment by Adirelle** [comment]
Here we go: https://github.com/Adirelle/react-event-promise
